// <auto-generated />
using ManageCategoriesApp2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManageCategoriesApp2.Migrations
{
    [DbContext(typeof(MyStockDBContext))]
    partial class MyStockDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ManageCategoriesApp2.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("CategoryId");

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Name 1"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Name 2"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Name 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
